# Generated by Django 4.2.16 on 2024-12-07 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.EmailField(max_length=254)),
                ('fecha_visualizacion', models.DateTimeField(blank=True, null=True)),
                ('accion', models.CharField(choices=[('Visto', 'Visto'), ('No Visto', 'No Visto')], default='No Visto', max_length=100)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correspondencia.documento')),
            ],
        ),
    ]
